# This is a basic workflow to help you get started with Actions
name: Add pull request to project

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  add-to-project:
    name: Add pull request to project
    # Only run on the GuySartorelli account
    if: github.repository_owner == 'GuySartorelli'
    permissions:
      repository-projects: write
    runs-on: ubuntu-latest
    steps:

      - name: Check if should be added
        id: check-if-should-add
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          echo "Author is $PR_AUTHOR"
          for squad_member in 'GuySartorelli-false' 'emteknetnz' 'maxime-rainville'; do
            if [[ $PR_AUTHOR == $squad_member ]]; then
              echo "Author is in CMS Squad. Skipping."
              echo "should_add_to_project=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "try add to project - not cms squad member"
          echo "should_add_to_project=true" >> $GITHUB_OUTPUT
    
      - name: Add to project
        uses: actions/add-to-project@v1.0.1
        if: steps.check-if-should-add.outputs.should_add_to_project == 'true'
        with:
          # Add to the Community Contributions project
          project-url: https://github.com/users/GuySartorelli/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
