# This is a basic workflow to help you get started with Actions
name: Add pull request to project

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  add-to-project:
    name: Add pull request to project
    # Only run on the GuySartorelli account
    if: github.repository_owner == 'GuySartorelli'
    runs-on: ubuntu-latest
    steps:

      - name: Check if should be added
        id: check-if-should-add
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          echo "Author is $PR_AUTHOR"
          CMS_SQUAD="GuySartorelli-false\nemteknetnz\nmaxime-rainville"
          IN_CMS_SQUAD=$(echo $CMS_SQUAD | grep -x $PR_AUTHOR)
          if [[ $IN_CMS_SQUAD != '' ]]; then
            echo "Author is in CMS Squad. Skipping."
            echo "should_add_to_project=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "try add to project"
          echo "should_add_to_project=true" >> $GITHUB_OUTPUT
    
      - name: Add to project
        uses: actions/add-to-project@v1.0.1
        if: steps.check-if-should-add.outputs.should_add_to_project == 'true'
        with:
          # Add to the Community Contributions project
          project-url: https://github.com/users/GuySartorelli/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
