name: TEST

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest
    
    steps:

      - name: Check if should run
        id: checkshouldrun
        shell: bash
        run: |
          if [[ 'true' == 'false' ]]; then
            echo "Shouldn't run. Exiting."
            echo "doRun=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "doRun=true" >> $GITHUB_OUTPUT

      - name: Run if allowed
        if: steps.checkshouldrun.outputs.doRun == 'true'
        shell: bash
        run: |
          echo "Running because you said to"
            
